# Generated by Django 6.0.1 on 2026-01-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchprofile',
            name='created_by',
        ),
    ]
