# Generated by Django 6.0.1 on 2026-01-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='username',
        ),
    ]
