# Generated by Django 6.0.1 on 2026-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_studentprofile_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='encrypted_password',
            field=models.TextField(blank=True, help_text='Encrypted password.', null=True),
        ),
    ]
