# Generated by Django 6.0.1 on 2026-01-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_exam_question_studentexam_studentanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='statement',
            new_name='statement_1',
        ),
        migrations.AddField(
            model_name='question',
            name='statement_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
