# Generated by Django 6.0.1 on 2026-01-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_statement_question_statement_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='statement_1',
            new_name='statements',
        ),
        migrations.RemoveField(
            model_name='question',
            name='statement_2',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.studentexam'),
        ),
    ]
