# Generated by Django 6.0.1 on 2026-01-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_principalprofile_email_teacherprofile_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherSchedule',
            new_name='ScheduleMeet',
        ),
    ]
