# Generated by Django 6.0.1 on 2026-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_teacherschedule_schedulemeet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablechangerequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetablechangerequest',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetablechangerequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetablechangerequest',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
