# Generated by Django 6.0.1 on 2026-01-21 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_timetablechangerequest_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablechangerequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
