# Generated by Django 6.0.1 on 2026-01-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_studentprofile_balance_amount_monthlypayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
