# Generated by Django 6.0.1 on 2026-01-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_monthlypayment_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedmonthlypayment',
            name='reason',
        ),
    ]
